import type { SyllabusRef } from './curriculum'
import type { DatabaseTableName } from './databaseTables'

/**
 * Original practice questions for CAIE O Level Computer Science 2210 Paper 2
 * content that isn't pseudocode (Topics 9 and 10), so the interpreter can't
 * run them the way pseudocode runs — SQL questions instead get a live query
 * playground (see SqlPlayground.tsx) backed by the small real SQL engine in
 * src/sql/. Written from scratch to match the syllabus's own described
 * skills; not adapted from any real past paper (Cambridge does not permit
 * redistributing past-paper questions).
 */
export interface ReferenceQuestion {
  id: string
  title: string
  syllabusRef: SyllabusRef
  prompt: string
  answer: string
  /** SQL questions only: which sample table the playground should query. */
  table?: DatabaseTableName
}

export const referenceTopics = ['Databases (SQL)', 'Boolean Logic'] as const
export type ReferenceTopic = (typeof referenceTopics)[number]

export const referenceQuestions: Record<ReferenceTopic, ReferenceQuestion[]> = {
  'Databases (SQL)': [
    {
      id: 'sql-select-where',
      title: 'SELECT with a condition',
      syllabusRef: { section: '9', title: 'Databases' },
      prompt: `The Books table has fields: BookID, Title, Author, Genre, Price.

Write an SQL statement to list the Title and Author of every book in the "Fiction" genre that costs less than 15.`,
      answer: `SELECT Title, Author
FROM Books
WHERE Genre = "Fiction" AND Price < 15`,
      table: 'Books',
    },
    {
      id: 'sql-predict-output',
      title: 'Predict the query output',
      syllabusRef: { section: '9', title: 'Databases' },
      prompt: `Using the Books table, what is the output of:
SELECT Title FROM Books WHERE Genre = "SciFi" ORDER BY Price`,
      answer: `The Martian
Dune
Foundation

(Rows are filtered to Genre = "SciFi", then sorted ascending by Price: 11, 12, 14.)`,
      table: 'Books',
    },
    {
      id: 'sql-count-aggregate',
      title: 'COUNT and an aggregate condition',
      syllabusRef: { section: '9', title: 'Databases' },
      prompt: 'Using the Books table, write an SQL statement that outputs how many books have a Price greater than or equal to 10.',
      answer: `SELECT COUNT(*)
FROM Books
WHERE Price >= 10`,
      table: 'Books',
    },
    {
      id: 'sql-order-desc',
      title: 'ORDER BY, highest first',
      syllabusRef: { section: '9', title: 'Databases' },
      prompt: 'Using the Students table, write an SQL statement listing the Name and Mark of every student in form "4B", with the highest mark first.',
      answer: `SELECT Name, Mark
FROM Students
WHERE Form = "4B"
ORDER BY Mark DESC`,
      table: 'Students',
    },
    {
      id: 'sql-avg-aggregate',
      title: 'AVG with a condition',
      syllabusRef: { section: '9', title: 'Databases' },
      prompt: 'Using the Students table, write an SQL statement to find the average Mark of every student in form "4A".',
      answer: `SELECT AVG(Mark)
FROM Students
WHERE Form = "4A"`,
      table: 'Students',
    },
    {
      id: 'sql-or-condition',
      title: 'Combining conditions with OR',
      syllabusRef: { section: '9', title: 'Databases' },
      prompt: 'Using the Books table, write an SQL statement listing the Title of every book that is either "NonFiction", or costs more than 20.',
      answer: `SELECT Title
FROM Books
WHERE Genre = "NonFiction" OR Price > 20`,
      table: 'Books',
    },
    {
      id: 'sql-primary-key',
      title: 'Choosing a primary key',
      syllabusRef: { section: '9', title: 'Databases' },
      prompt:
        'The Students table uses StudentID as its primary key rather than Name. Explain why Name alone would be a poor choice of primary key, and why StudentID is better.',
      answer:
        'Name is not guaranteed to be unique — two students could share a name, so it cannot reliably identify a single record on its own. StudentID is generated by the system so every value is guaranteed unique, making it a safe way to identify exactly one row.',
      table: 'Students',
    },
  ],
  'Boolean Logic': [
    {
      id: 'logic-truth-table-and-or',
      title: 'Complete the truth table',
      syllabusRef: { section: '10', title: 'Boolean logic' },
      prompt: `Complete the truth table for X = (A AND B) OR NOT C

A | B | C | X
0 | 0 | 0 | ?
0 | 0 | 1 | ?
1 | 1 | 0 | ?
1 | 1 | 1 | ?`,
      answer: `A | B | C | X
0 | 0 | 0 | 1   (NOT C = 1)
0 | 0 | 1 | 0   (A AND B = 0, NOT C = 0)
1 | 1 | 0 | 1   (A AND B = 1)
1 | 1 | 1 | 1   (A AND B = 1)`,
    },
    {
      id: 'logic-derive-expression',
      title: 'Derive an expression from a truth table',
      syllabusRef: { section: '10', title: 'Boolean logic' },
      prompt: `A logic system has two inputs, A and B, and output X:

A | B | X
0 | 0 | 0
0 | 1 | 1
1 | 0 | 1
1 | 1 | 0

Write the Boolean expression for X, and name the single logic gate that matches this behaviour.`,
      answer:
        'X = (A AND NOT B) OR (NOT A AND B). This is the XOR pattern — X is TRUE only when A and B differ — so a single XOR gate produces this truth table.',
    },
    {
      id: 'logic-nand-equivalent',
      title: 'Identify an equivalent gate',
      syllabusRef: { section: '10', title: 'Boolean logic' },
      prompt: 'Which single logic gate is equivalent to NOT (A AND B)? State its name and describe when its output is 0.',
      answer:
        'NAND. Its output is 0 only when both inputs are 1 (i.e. exactly when A AND B would be TRUE) — for every other input combination the output is 1.',
    },
    {
      id: 'logic-nor-gate',
      title: 'NOR: the other combined gate',
      syllabusRef: { section: '10', title: 'Boolean logic' },
      prompt: 'Which single logic gate is equivalent to NOT (A OR B)? State its name and describe when its output is 1.',
      answer:
        'NOR. Its output is 1 only when both inputs are 0 (i.e. exactly when A OR B would be FALSE) — for every other input combination the output is 0.',
    },
    {
      id: 'logic-three-input',
      title: 'A three-input expression',
      syllabusRef: { section: '10', title: 'Boolean logic' },
      prompt: 'Evaluate X = A OR (B AND C) for A = 0, B = 1, C = 0. Show your working.',
      answer: 'B AND C = 1 AND 0 = 0. X = A OR 0 = 0 OR 0 = 0. So X = 0.',
    },
    {
      id: 'logic-three-input-full-table',
      title: 'Complete a full three-input truth table',
      syllabusRef: { section: '10', title: 'Boolean logic' },
      prompt: `Complete the full 8-row truth table for X = (A OR B) AND NOT C

A | B | C | X
0 | 0 | 0 | ?
0 | 0 | 1 | ?
0 | 1 | 0 | ?
0 | 1 | 1 | ?
1 | 0 | 0 | ?
1 | 0 | 1 | ?
1 | 1 | 0 | ?
1 | 1 | 1 | ?`,
      answer: `A | B | C | X
0 | 0 | 0 | 0
0 | 0 | 1 | 0
0 | 1 | 0 | 1
0 | 1 | 1 | 0
1 | 0 | 0 | 1
1 | 0 | 1 | 0
1 | 1 | 0 | 1
1 | 1 | 1 | 0

(X is 1 only when at least one of A/B is 1 AND C is 0.)`,
    },
  ],
}
